// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatSummary
 */
export interface ChatSummary {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ChatSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChatSummary
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatSummary
     */
    preview?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChatSummary
     */
    lastRole?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ChatSummary
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the ChatSummary interface.
 */
export function instanceOfChatSummary(value: object): value is ChatSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ChatSummaryFromJSON(json: any): ChatSummary {
    return ChatSummaryFromJSONTyped(json, false);
}

export function ChatSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSummary {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'preview': json['preview'] == null ? undefined : json['preview'],
        'lastRole': json['last_role'] == null ? undefined : json['last_role'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ChatSummaryToJSON(json: any): ChatSummary {
    return ChatSummaryToJSONTyped(json, false);
}

export function ChatSummaryToJSONTyped(value?: ChatSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'title': value['title'],
        'preview': value['preview'],
        'last_role': value['lastRole'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

