// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatSummary } from './ChatSummary';
import {
    ChatSummaryFromJSON,
    ChatSummaryFromJSONTyped,
    ChatSummaryToJSON,
    ChatSummaryToJSONTyped,
} from './ChatSummary';

/**
 * 
 * @export
 * @interface ListChatsResponse
 */
export interface ListChatsResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<ChatSummary>}
     * @memberof ListChatsResponse
     */
    chats: Array<ChatSummary>;
}

/**
 * Check if a given object implements the ListChatsResponse interface.
 */
export function instanceOfListChatsResponse(value: object): value is ListChatsResponse {
    if (!('chats' in value) || value['chats'] === undefined) return false;
    return true;
}

export function ListChatsResponseFromJSON(json: any): ListChatsResponse {
    return ListChatsResponseFromJSONTyped(json, false);
}

export function ListChatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListChatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'chats': ((json['chats'] as Array<any>).map(ChatSummaryFromJSON)),
    };
}

export function ListChatsResponseToJSON(json: any): ListChatsResponse {
    return ListChatsResponseToJSONTyped(json, false);
}

export function ListChatsResponseToJSONTyped(value?: ListChatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'chats': ((value['chats'] as Array<any>).map(ChatSummaryToJSON)),
    };
}

