// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  UserCreated,
} from '../models/index';
import {
    UserCreatedFromJSON,
    UserCreatedToJSON,
} from '../models/index';

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Handle GitHub OAuth callback but redirect to frontend with token in querystring.  This route does NOT set the cookie on the backend. Instead it redirects the user to the frontend page `/auth/set-cookie-client?token=...` which will persist the token as a cookie from the frontend server code.
     * Github Callback
     */
    async githubCallbackAuthGithubCallbackGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Handle GitHub OAuth callback but redirect to frontend with token in querystring.  This route does NOT set the cookie on the backend. Instead it redirects the user to the frontend page `/auth/set-cookie-client?token=...` which will persist the token as a cookie from the frontend server code.
     * Github Callback
     */
    async githubCallbackAuthGithubCallbackGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.githubCallbackAuthGithubCallbackGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Initiate GitHub OAuth login flow.
     * Github Login
     */
    async githubLoginAuthGithubLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Initiate GitHub OAuth login flow.
     * Github Login
     */
    async githubLoginAuthGithubLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.githubLoginAuthGithubLoginGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Logout user by clearing the JWT cookie.
     * Logout
     */
    async logoutAuthLogoutGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Logout user by clearing the JWT cookie.
     * Logout
     */
    async logoutAuthLogoutGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.logoutAuthLogoutGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Me
     */
    async meAuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserCreated>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserCreatedFromJSON(jsonValue));
    }

    /**
     * Me
     */
    async meAuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserCreated> {
        const response = await this.meAuthMeGetRaw(initOverrides);
        return await response.value();
    }

}
