// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatRequest,
  CreateNewChatResponse,
  GetChatMessagesResponse,
  HTTPValidationError,
  ListChatsResponse,
} from '../models/index';
import {
    ChatRequestFromJSON,
    ChatRequestToJSON,
    CreateNewChatResponseFromJSON,
    CreateNewChatResponseToJSON,
    GetChatMessagesResponseFromJSON,
    GetChatMessagesResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ListChatsResponseFromJSON,
    ListChatsResponseToJSON,
} from '../models/index';

export interface DeleteChatEndpointChatChatIdDeleteRequest {
    chatId: string;
}

export interface GetChatMessagesChatChatIdGetRequest {
    chatId: string;
}

export interface GetUserChatsChatGetRequest {
    limit?: number | null;
}

export interface HandleChatDataChatPostRequest {
    chatRequest: ChatRequest;
    protocol?: any;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Create a new chat and return its ID.
     * Create New Chat
     */
    async createNewChatChatCreatePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateNewChatResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateNewChatResponseFromJSON(jsonValue));
    }

    /**
     * Create a new chat and return its ID.
     * Create New Chat
     */
    async createNewChatChatCreatePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateNewChatResponse> {
        const response = await this.createNewChatChatCreatePostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a chat and all its messages.
     * Delete Chat Endpoint
     */
    async deleteChatEndpointChatChatIdDeleteRaw(requestParameters: DeleteChatEndpointChatChatIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatId'] == null) {
            throw new runtime.RequiredError(
                'chatId',
                'Required parameter "chatId" was null or undefined when calling deleteChatEndpointChatChatIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/{chat_id}`;
        urlPath = urlPath.replace(`{${"chat_id"}}`, encodeURIComponent(String(requestParameters['chatId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a chat and all its messages.
     * Delete Chat Endpoint
     */
    async deleteChatEndpointChatChatIdDelete(requestParameters: DeleteChatEndpointChatChatIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteChatEndpointChatChatIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Load chat messages by chat ID.
     * Get Chat Messages
     */
    async getChatMessagesChatChatIdGetRaw(requestParameters: GetChatMessagesChatChatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetChatMessagesResponse>> {
        if (requestParameters['chatId'] == null) {
            throw new runtime.RequiredError(
                'chatId',
                'Required parameter "chatId" was null or undefined when calling getChatMessagesChatChatIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat/{chat_id}`;
        urlPath = urlPath.replace(`{${"chat_id"}}`, encodeURIComponent(String(requestParameters['chatId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetChatMessagesResponseFromJSON(jsonValue));
    }

    /**
     * Load chat messages by chat ID.
     * Get Chat Messages
     */
    async getChatMessagesChatChatIdGet(requestParameters: GetChatMessagesChatChatIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetChatMessagesResponse> {
        const response = await this.getChatMessagesChatChatIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Return chat summaries for the authenticated user.
     * Get User Chats
     */
    async getUserChatsChatGetRaw(requestParameters: GetUserChatsChatGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListChatsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/chat`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListChatsResponseFromJSON(jsonValue));
    }

    /**
     * Return chat summaries for the authenticated user.
     * Get User Chats
     */
    async getUserChatsChatGet(requestParameters: GetUserChatsChatGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListChatsResponse> {
        const response = await this.getUserChatsChatGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stream a message response from OpenAI, storing messages in database.
     * Handle Chat Data
     */
    async handleChatDataChatPostRaw(requestParameters: HandleChatDataChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['chatRequest'] == null) {
            throw new runtime.RequiredError(
                'chatRequest',
                'Required parameter "chatRequest" was null or undefined when calling handleChatDataChatPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['protocol'] != null) {
            queryParameters['protocol'] = requestParameters['protocol'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/chat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatRequestToJSON(requestParameters['chatRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream a message response from OpenAI, storing messages in database.
     * Handle Chat Data
     */
    async handleChatDataChatPost(requestParameters: HandleChatDataChatPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.handleChatDataChatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
