"""empty message

Revision ID: 42135c2e7372
Revises: 3e7a4a42b100
Create Date: 2025-11-05 11:30:54.820998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "42135c2e7372"
down_revision: Union[str, Sequence[str], None] = "3e7a4a42b100"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Consolidated addition of timestamp columns. Keep a server_default of now()
    # so subsequent migrations can safely alter nullability.
    op.add_column(
        "chat",
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("now()"),
        ),
    )
    op.add_column(
        "chat",
        sa.Column(
            "changed_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("now()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "changed_at")
    op.drop_column("chat", "created_at")
    # ### end Alembic commands ###
