"""empty message

Revision ID: 609fd7ee3d55
Revises: 42135c2e7372
Create Date: 2025-11-06 15:23:27.049455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "609fd7ee3d55"
down_revision: Union[str, Sequence[str], None] = "42135c2e7372"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column(
            "created_at", sa.DateTime(), nullable=True, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "chat",
        sa.Column(
            "changed_at", sa.DateTime(), nullable=True, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat", "changed_at")
    op.drop_column("chat", "created_at")
    # ### end Alembic commands ###
