"""empty message

Revision ID: 93fa71276d73
Revises: e57742089c24
Create Date: 2025-11-12 15:41:49.413501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel   


# revision identifiers, used by Alembic.
revision: str = '93fa71276d73'
down_revision: Union[str, Sequence[str], None] = 'e57742089c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'title')
    # ### end Alembic commands ###
