"""empty message

Revision ID: e46cfb8c5ee8
Revises: 609fd7ee3d55
Create Date: 2025-11-06 21:37:43.198089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel   
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46cfb8c5ee8'
down_revision: Union[str, Sequence[str], None] = '609fd7ee3d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('message', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('message', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_message_role'), 'message', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_role'), table_name='message')
    op.drop_column('message', 'content')
    op.drop_column('message', 'role')
    op.alter_column('chat', 'changed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
