"""empty message

Revision ID: e57742089c24
Revises: cf99400aa468
Create Date: 2025-11-09 17:14:19.428474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel   


# revision identifiers, used by Alembic.
revision: str = 'e57742089c24'
down_revision: Union[str, Sequence[str], None] = 'cf99400aa468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
